# Dialog window set up for BIFS parameters

from PyQt4 import QtCore, QtGui

class Param_Fourier_Space_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Parameter Space Function")
        Dialog.resize(200, 200)
        self.layout = QtGui.QVBoxLayout(self)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.param_spaceSetUp = QtGui.QLabel("K-Space Parameter Function", self)
        self.param_spaceBox = QtGui.QComboBox(self)
        # self.param_spaceBox.setCurrentIndex(self.parent().param_func)
        self.param_spaceBox.addItems(self.parent().mybifs.param_func_choices)
        self.param_spaceBox.setCurrentIndex(self.parent().mybifs.param_func_choices.index(self.parent().mybifs.param_func_type))
        self.decay_label = QtGui.QLabel('Decay Exponent:', self)
        self.decay = QtGui.QLineEdit(str(self.parent().mybifs.decay))
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.layout.addWidget(self.param_spaceSetUp)
        self.layout.addWidget(self.param_spaceBox)
        self.layout.addWidget(self.decay_label)
        self.layout.addWidget(self.decay)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

class Prior_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Prior Distribution")
        Dialog.resize(200, 200)
        self.layout = QtGui.QVBoxLayout(self)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.priorSetUp = QtGui.QLabel("Prior Distribution", self)
        self.priorBox = QtGui.QComboBox(self)
        # self.priorBox.setCurrentIndex(self.parent().param_func)
        self.priorBox.addItems(self.parent().mybifs.prior_choices)
        self.priorBox.setCurrentIndex(self.parent().mybifs.prior_choices.index(self.parent().mybifs.prior))
        self.scale_label = QtGui.QLabel('Scale:', self)
        self.scale = QtGui.QLineEdit(str(self.parent().mybifs.prior_scale))
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.layout.addWidget(self.priorSetUp)
        self.layout.addWidget(self.priorBox)
        self.layout.addWidget(self.scale_label)
        self.layout.addWidget(self.scale)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

class Likelihood_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Likelihood Distribution")
        Dialog.resize(200, 200)
        self.layout = QtGui.QVBoxLayout(self)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.likelihoodSetUp = QtGui.QLabel("Likelihood Distribution", self)
        self.likelihoodBox = QtGui.QComboBox(self)
        # self.priorBox.setCurrentIndex(self.parent().param_func)
        self.likelihoodBox.addItems(self.parent().mybifs.likelihood_choices)
        self.likelihoodBox.setCurrentIndex(self.parent().mybifs.likelihood_choices.index(self.parent().mybifs.likelihood))
        self.scale_label = QtGui.QLabel('Scale:', self)
        self.scale = QtGui.QLineEdit(str(self.parent().mybifs.likelihood_scale))
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.layout.addWidget(self.likelihoodSetUp)
        self.layout.addWidget(self.likelihoodBox)
        self.layout.addWidget(self.scale_label)
        self.layout.addWidget(self.scale)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

class Slice3D_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Select 3D Slice to View")
        Dialog.resize(200, 200)
        self.layout = QtGui.QVBoxLayout(self)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.slice_index_label = QtGui.QLabel('Slice Axis Index:', self)
        self.slice_index = QtGui.QLineEdit(str(self.parent().mybifs.view3Dslice[0]))
        self.slice_percent_label = QtGui.QLabel('Percent Along Index:', self)
        self.slice_percent = QtGui.QLineEdit(str(self.parent().mybifs.view3Dslice[1]))
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.layout.addWidget(self.slice_index_label)
        self.layout.addWidget(self.slice_index)
        self.layout.addWidget(self.slice_percent_label)
        self.layout.addWidget(self.slice_percent)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

class AddBump_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Add K-Space Bump Filter")
        Dialog.resize(300, 300)
        self.layout = QtGui.QVBoxLayout(self)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.addBumpKeySetUp = QtGui.QLabel("Add Bump", self)
        self.addBumpKeyBox = QtGui.QComboBox(self)
        self.addBumpKeyBox.addItems(self.parent().mybifs.bump_types)
        self.addBumpKeyBox.setCurrentIndex(self.parent().mybifs.bump_types.index(self.parent().mybifs.bump_default_type))
        self.Position_label = QtGui.QLabel('Position,fraction of Kmax:', self)
        self.Position = QtGui.QLineEdit()
        self.Amplitude_label = QtGui.QLabel('Amplitude,fraction of Pfuncmax:', self)
        self.Amplitude = QtGui.QLineEdit()
        self.Width_label = QtGui.QLabel('Width,fraction of Kmax:', self)
        self.Width = QtGui.QLineEdit()
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.layout.addWidget(self.addBumpKeySetUp)
        self.layout.addWidget(self.addBumpKeyBox)
        self.layout.addWidget(self.Position_label)
        self.layout.addWidget(self.Position)
        self.layout.addWidget(self.Amplitude_label)
        self.layout.addWidget(self.Amplitude)
        self.layout.addWidget(self.Width_label)
        self.layout.addWidget(self.Width)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

class DeleteBump_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Delete K-Space Bump Filter")
        Dialog.resize(300, 200)
        self.layout = QtGui.QVBoxLayout(self)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.deleteBumpKeySetUp = QtGui.QLabel("Delete Bump", self)
        self.deleteBumpKeyBox = QtGui.QComboBox(self)
        self.deleteBumpKeyBox.addItems(self.parent().bumplist)
        self.deleteBumpKeyBox.setCurrentIndex(self.parent().bumplist.index(self.parent().bumplist[0]))
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.layout.addWidget(self.deleteBumpKeySetUp)
        self.layout.addWidget(self.deleteBumpKeyBox)
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)
